### ISSUE TITLE
Mus call on main thread.

### ISSUE THREAD

**Issue by mrmurphy** [DamnWidget/SublimePySide#1]
Hey! I'm really interested in using this, but after cloning the repo, restarting sublime and trying to make a new project from template, I get this error: 

```
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

**Comment by DamnWidget** [comment]
Can you give me more information? Which system are you running, Linux, Windows or Mac OS X?. Which version of ST2?

**Comment by mrmurphy** [comment]
Sure! Sorry:

Mac OS X Lion,
ST 2 2.0.1 Build 2217

Anything else? It's using built-in Python 2.6.

**Comment by DamnWidget** [comment]
Ok, thank you, I'll work on it.

**Comment by DamnWidget** [comment]
Fixed, this should work fine now.

**Comment by mrmurphy** [comment]
And so it does! Thank you!
