### ISSUE TITLE
Cannot Create New Project

### ISSUE THREAD

**Issue by wngrtn** [DamnWidget/SublimePySide#2]
Tools -> PySide QT -> Create Project does not do anything for me.

I am using a clean install of Sublime Text 2.0.1 (Build 2217). I only added PackageControl and then SublimeRope and PySide via PackageControl. I tried on Mac OS X 10.7, on 10.8, and on Ubuntu 12.04.

**Comment by DamnWidget** [comment]
Hi @wngrtn I just reinstall my ST2 with PC and PySide and it's working nice form me on Mac OS X 10.7

Can you give me more details?. Are you using the zipped Python version that come already with ST2 or you are using your own?.

Can you add a report from the Python console?

Thanks.

**Comment by wngrtn** [comment]
Hi!

I apologize about being so unspecific in my last post. Clearly, I could have known that looking at the console was a good point to start :)

Here is what I get when I try to create a project:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./sublime_pyside.py", line 77, in run
  File "./sublime_pyside.py", line 87, in __init__
  File "./sublime_pyside.py", line 189, in get_template_list
IOError: [Errno 2] No such file or directory: '/Users/[...]/Library/Application Support/Sublime Text 2/Packages/SublimePySide/data/templates/templates.lst'
```

Something seems to be wrong with the path of the PySide installation. The error message refers to `Packages/SublimePySide` but the PySide is installed in `Packages/PySide`. I used packaged control to install it.

**Comment by DamnWidget** [comment]
I know where the problem is, I have a lot of things to do today but I will try to fix it ASAP. 

Thank you very much for the feedback.

**Comment by DamnWidget** [comment]
Fixed

**Comment by wngrtn** [comment]
Working just fine now. Thanks for fixing this so quickly!

**Comment by DamnWidget** [comment]
No problem. You are welcome.
