### ISSUE TITLE
Project creation not working in Windows

### ISSUE THREAD

**Issue by ghost** [DamnWidget/SublimePySide#5]
When I create a Project in Windows, the path contains single backslashes, so Sublime complains about  an invalid escape, changing the path to use double backslashes allows to open the project.

**Comment by DamnWidget** [comment]
This should be fixed now. Can you confirm it?

**Comment by ghost** [comment]
New project working as expected, If I have a usage question where is the correct place to do it?

**Comment by DamnWidget** [comment]
Hi

You can leave it here or you can just send me an email.
